#\u7AEF\u53E3\u53F7
# server:
#   port: 8081
  #\u5E94\u7528\u540D
spring:
  application:
    name: eureka-client02
  #\u6570\u636E\u5E93\u914D\u7F6E
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      #\u914D\u7F6E\u76D1\u542C\u4F7F\u7528\u65E5\u5FD7
      filters: stat,wall,slf4j
      initialization-mode: always
#\u5411\u6307\u5B9A\u670D\u52A1\u4E2D\u5FC3\u6CE8\u518C
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#\u914D\u7F6E\u65E5\u5FD7\u7B49\u7EA7\uFF0C\u4EE5\u53CA\u626B\u63CF\u6307\u5B9A\u7684\u5305
logging:
  level:
    com: debug
#\u914D\u7F6Emybatis\u914D\u7F6E\u6587\u4EF6\u626B\u63CF\u8DEF\u5F84
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml